cluster.name: "elk"
network.host: 0.0.0.0 # Для корректной работы внутри контейнера
node.name: netology_test
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch
path.repo: ["/usr/share/elasticsearch/snapshots"]
xpack.security.enabled: false # Для поддержки функционала, обеспечивающего безопасность кластера
xpack.license.self_generated.type: basic # Типа лицензии "basic" для наших нужд хватит с головой