-- DO $$ BEGIN 

CREATE TABLE IF NOT EXISTS Orders
(
    ID SERIAL PRIMARY KEY,
    Name VARCHAR(255),
    Price INTEGER
);

CREATE TABLE IF NOT EXISTS Clients
(
    ID SERIAL PRIMARY KEY,
    Name VARCHAR(255),
    Country VARCHAR(255),
    Order_ID INTEGER CONSTRAINT Client_Order_FK REFERENCES Orders (ID) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE INDEX Clients_Country ON Clients(Country);

CREATE USER "$DB_USER" WITH PASSWORD '$DB_PASSWORD';
REVOKE ALL PRIVILEGES ON DATABASE "$DB_NAME" from "$DB_USER";

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA "public" to "$DB_USER";
-- GRANT USAGE, SELECT ON SEQUENCE clients_id_seq TO user1;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA "public" TO "$DB_USER";

-- GRANT SELECT, INSERT, UPDATE, DELETE ON orders, clients TO "$DB_USER";
-- GRANT ALL ON Orders TO "$DB_USER";
-- GRANT ALL ON Clients TO "$DB_USER";
GRANT CONNECT ON DATABASE "$DB_NAME" TO "$DB_USER";

GRANT USAGE ON SCHEMA public TO "$DB_USER";

-- END $$;

CREATE OR REPLACE PROCEDURE UpdateClient(ClientName VARCHAR(255), OrderName VARCHAR(255))
LANGUAGE SQL
AS $$
	UPDATE Clients 
	SET Order_id = (SELECT ID from Orders WHERE Orders.name=OrderName) 
	WHERE Clients.Name=ClientName;
$$;