# Блоки и условия
Мы можем разделить задания для CentOS и Ubuntu создав 2 блока и прописать условия выполнения
---
- name: InstallApache and copy foto
  hosts: all
  become: yes

  vars:
    source_file: /home/ka/ansible/index.html
    destin_file: /var/www/html

  tasks:
    - name: Check version OS
      debug: var="ansible_os_family"

    - block: # ====BLOCK FOR REDHAT====
        - name: Install Apache Web Server for RedHat
          yum: name=httpd state=latest

        - name: Copy My index.html
          copy: src={{ source_file }} dest={{ destin_file }} mode=555
          notify: Restarted Apache_RedHat

        - name: Start WebServer for RedHat
          service: name=httpd state=started enabled=yes
      when: ansible_os_family == "RedHat"

    - block: # ====BLOCK FOR UBUNTU====
        - name: Install Apache WebServer for Ubuntu
          apt: name=apache2 state=latest

        - name: Copy My index.html
          copy: src={{ source_file }} dest={{ destin_file }} mode=555
          notify: Restarted Apache_Ubuntu

        - name: Start WebServer for Ubuntu
          service: name=apache2 state=started enabled=yes
      when: ansible_os_family == "Debian"

  handlers:
    - name: Restarted Apache_RedHat
      service: name=httpd state=restarted

    - name: Restarted Apache_Ubuntu
      service: name=apache2 state=restarted
