---
- name: LightHouse
  hosts: lighthouse
  tasks:
    - name: Create LightHouse config
      ansible.builtin.template:
        src: templates/lighthouse.conf.j2
        dest: /etc/nginx/conf.d/default.conf
        mode: "0644"
    #           notify: reload-nginx

    - name: Enable and start LightHouse service
      ansible.builtin.systemd:
        name: nginx
        enabled: true
        state: started

- name: ClickHouse
  hosts: clickhouse
  tasks:
    - name: Enable and start ClickHouse service
      ansible.builtin.systemd:
        name: clickhouse-server
        enabled: true
        state: started

    - name: Create ClickHouse database
      ansible.builtin.command: clickhouse-client -q 'create database logs;'
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0

- name: Vector
  hosts: vector
  tasks:
    - name: Create Vector config by template
      ansible.builtin.template:
        src: vector.toml.j2
        dest: /etc/vector/vector.toml
        mode: "0644"

    - name: Enable and start Vector service
      ansible.builtin.systemd:
        name: vector
        enabled: true
        state: started
