version: '3.1'

services:
  db:
    build: ./db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 1234567
    volumes:
      - ./databases:/var/lib/mysql
  adminer:
    build: ./adminer
    restart: always
    ports:
      - 8083:8080