---
#============================== The Beginning of the Copyright Notice ==========================================================
# The AUTHOR of this file and the owner of exclusive rights is Alexander Borisovich Prokopyev 
# born on December 20, 1977 resident of the city of Kurgan, Russia;
# Series and Russian passport number (only the last two digits for each one): **22-****91
# Russian Individual Taxpayer Number of the AUTHOR (only the last four digits): ********2007
# Russian Insurance Number of Individual Ledger Account of the AUTHOR (only the last five digits): ***-***-859 04
# Copyright (C) Alexander B. Prokopyev, 2023, All Rights Reserved.
# Contact:     a.prokopyev.resume at gmail dot com
#
# All source code contained in this file is protected by copyright law.
# This file is available under AGPL v3 (GNU Affero General Public License): https://www.gnu.org/licenses/agpl-3.0.en.html
# PROVIDED FOLLOWING RESTRICTIONS APPLY:
# Nobody except the AUTHOR may alter or remove this copyright notice from any legal copies of this file content.
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an
# AS IS BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.
#================================= The End of the Copyright Notice =============================================================

- hosts: localhost
  gather_facts: no
  connection: local
  vars_files: # Load global variables only once before playbook execution
    - vars/secrets.yml
    - vars/docker-compose.env.json # converted from env to JSON by env2json.py script
  collections: community.docker

  tasks:
    - name: ===> WORK_6_3 
      debug:
        msg: 06-db-03-mysql

    - name: Load env variables (dynamically at this point here) earlier converted from env to JSON by env2json.py script
      include_vars:
        file: vars/admin.env.json
        name: AdminEnv

    - name: Load user.env
      include_vars:
        file: vars/user.env.json
        name: UserEnv

    - include_tasks:
        file: task1.yml
      tags:
      - task1

    - include_tasks:
        file: task2.yml
      tags:
      - task2

    - include_tasks:
        file: task3.yml
      tags:
      - task3

#    - include_tasks:
#        file: task4.yml
#      tags:
#      - task4

