---
#- name: Prepare and start target containers
#  import_playbook: on_start.yml

- name: "08-ansible-02-playbook for ClickHouse"
  hosts: clickhouse
  tasks:
#    - name: Enable and start clickhouse service
#      ansible.builtin.service:
#        name: clickhouse-server
#        state: started
#        enabled: true

    - name: Enable and start ClickHouse service
      ansible.builtin.systemd:
        name: clickhouse-server
        enabled: true
        state: started

    - name: Create ClickHouse database
      ansible.builtin.command: clickhouse-client -q 'create database logs;'
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc != 82
      changed_when: create_db.rc == 0

- name: "08-ansible-02-playbook for Vector"
  hosts: vector
  tasks:
    - name: Create Vector config by template
      ansible.builtin.template:
        src: vector.toml.j2
        dest: /etc/vector/vector.toml
        mode: "0644"

#    - name: Enable and start Vector service from shell
#      ansible.builtin.shell: |
#        systemctl enable vector;
#        systemctl start vector;

    - name: Enable and start Vector service
      ansible.builtin.systemd:
        name: vector
        enabled: true
        state: started       
