version: "3"
services:
        mysql:
                image: mysql
                ports:
                        - 3306:3306
                environment:
                        - MYSQL_ROOT_PASSWORD=vecrek
        nginx:
                image: user1/nginxtest
                ports:
                        - 8009:80
                links:
                        - php
                volumes:
                        - /home/ka/VS_code/Base/KaDevOps/YoDo/Docker/dockertest/www:/var/www
        php:
                image: macedigital/phpfpm
                volumes:
                        - /home/ka/VS_code/Base/KaDevOps/YoDo/Docker/dockertest/www:/var/www
