---
- name: Enable and start ClickHouse service
  ansible.builtin.systemd:
    name: clickhouse-server
    enabled: true
    state: started

- name: Create ClickHouse database
  ansible.builtin.command: clickhouse-client -q 'create database logs;'
  register: create_db
  failed_when: create_db.rc != 0 and create_db.rc != 82
  changed_when: create_db.rc == 0

